# Generated by Django 5.0.2 on 2024-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plates',
            field=models.IntegerField(default=0),
        ),
    ]
