# Generated by Django 5.0.2 on 2024-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_profile_plates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_amt',
            field=models.IntegerField(default=0),
        ),
    ]
