# Generated by Django 5.0.2 on 2024-04-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_profile_user_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_amt',
            new_name='lunch_amt',
        ),
    ]
